-- dbline.sql - schema for Travel Bot
CREATE DATABASE IF NOT EXISTS `dbline` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `dbline`;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(64) NOT NULL,
  displayName VARCHAR(255) DEFAULT NULL,
  lastSeen BIGINT DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS context (
  userId VARCHAR(64) NOT NULL,
  state VARCHAR(255) DEFAULT NULL,
  meta JSON DEFAULT NULL,
  PRIMARY KEY (userId),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS history (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  userId VARCHAR(64) DEFAULT NULL,
  eventType VARCHAR(64) DEFAULT NULL,
  payload JSON DEFAULT NULL,
  createdAt BIGINT DEFAULT NULL,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
